dependencies:
  /content/pages/index.html:
  - /content/pages/index.html
  - /dist/css/main.min.css
  - /dist/js/main.min.js
  - /source/images/appstore-illo.svg
  - /source/images/appstore.svg
  - /source/images/beta-illo.svg
  - /source/images/beta.svg
  - /source/images/bitrise-logo.png
  - /source/images/circleci-logo.png
  - /source/images/codesigning-illo.svg
  - /source/images/codesigning.svg
  - /source/images/fastlane-logo-lockup.png
  - /source/images/favicon.ico
  - /source/images/google-developers-lockup-color.svg
  - /source/images/google-developers-logo-lockup.svg
  - /source/images/ic_appstore.svg
  - /source/images/ic_beta.svg
  - /source/images/ic_codesigning.svg
  - /source/images/ic_screenshots.svg
  - /source/images/jenkins-logo.png
  - /source/images/menu-close.svg
  - /source/images/menu-hamburger.svg
  - /source/images/quotation-mark.svg
  - /source/images/screenshots-illo.svg
  - /source/images/screenshots.svg
  - /source/images/travis-logo.png
  - /source/images/twitter-logo.svg
  - /views/partials/_footer.html
  - /views/partials/_header.html
objects: {}
